import test from 'node:test';
import assert from 'node:assert/strict';
import { importTs } from './load-ts.mjs';
const f = await importTs('../lib/formatters.ts');
test('formatSignedPercent shows sign', () => assert.equal(f.formatSignedPercent(0.124), '+12.4%'));
test('formatCompactUsd supports null', () => assert.equal(f.formatCompactUsd(null), 'N/A'));
test('formatSignedUsd negative flows', () => assert.equal(f.formatSignedUsd(-42000000).startsWith('-$'), true));
test('formatAddress', () => assert.equal(f.formatAddress('0x1234567890abcdef').includes('...'), true));
test('formatTxHash', () => assert.equal(f.formatTxHash('0x1234567890abcdef').includes('...'), true));
test('formatTimeAgo', () => assert.equal(f.formatTimeAgo(new Date().toISOString()).startsWith('Updated'), true));
