import test from 'node:test';
import assert from 'node:assert/strict';
import { importTs } from './load-ts.mjs';
const m = await importTs('../lib/metrics.ts');
test('safeChangePct handles zero previous', () => assert.equal(m.safeChangePct(100, 0), null));
test('rolling sums include negative flows', () => assert.equal(m.rolling_5d([10,-5,2,3,-1]), 9));
test('cumulative sums preserve null gaps', () => assert.deepEqual(m.cumulative_sum([1,2,null,-3]), [1,3,3,0]));
test('market share safe', ()=>assert.equal(m.market_share(5,10),0.5));
test('rank change positive means rank improved', ()=>assert.equal(m.rank_change(2,5),3));
test('streaks count latest direction', ()=>assert.equal(m.streak_count([1,2,-1,-2]),2));
test('supply pressure returns null on zero volume', ()=>assert.equal(m.supply_pressure_score(100,0),null));
test('supply pressure ratio', ()=>assert.equal(m.supply_pressure_score(100,20),5));
test('long/short imbalance', ()=>assert.equal(m.long_short_imbalance(70,30),0.4));
