"use client";

import { getInitials } from "@/lib/chainLogos";
import { formatUsd } from "@/lib/format";
import type { ChainRevenueRow } from "@/lib/defillama";

function rowLayoutClass(count: number) {
  if (count > 15) return "mt-6 grid gap-2";
  if (count > 10) return "mt-7 grid gap-2.5";
  return "mt-9 grid gap-3.5";
}

function titleSizeClass(count: number) {
  if (count > 15) return "mt-3 text-3xl font-black leading-[0.95] tracking-[-0.055em] text-slate-950 md:text-4xl";
  return "mt-3 text-4xl font-black leading-[0.95] tracking-[-0.055em] text-slate-950 md:text-5xl";
}

export function ShareCard({ rows, timeframe, updatedAt, source }: { rows: ChainRevenueRow[]; timeframe: string; updatedAt: string; source: string }) {
  const leader = rows[0];
  const runnerUp = rows[1];
  const count = rows.length;

  return (
    <div id="share-card" className="card-grid-bg relative overflow-hidden rounded-[34px] border border-slate-200 bg-white p-8 shadow-soft md:p-10">
      <div className="absolute right-8 top-8 rounded-full border border-slate-200 bg-white/95 px-4 py-2 text-xs font-black tracking-[-0.02em] text-slate-950 shadow-sm">
        learnDeFi
      </div>

      <div className="max-w-[74%]">
        <p className="text-sm font-black uppercase tracking-[0.24em] text-slate-400">Chain Revenue</p>
        <h2 className={titleSizeClass(count)}>Top {count} chains by {timeframe} revenue</h2>
        <p className="mt-4 max-w-xl text-base font-medium leading-7 text-slate-500">Chain-level revenue captured by networks. App and protocol revenues are excluded.</p>
      </div>

      <div className={rowLayoutClass(count)}>
        {rows.map((row) => {
          const pct = leader?.value ? Math.max(7, (row.value / leader.value) * 100) : 0;
          const compact = count > 10;
          return (
            <div key={row.name} className="grid grid-cols-[34px_minmax(128px,170px)_1fr_104px] items-center gap-3 md:grid-cols-[36px_190px_1fr_120px]">
              <div className="text-right text-sm font-black text-slate-400">{row.rank}</div>
              <div className="flex min-w-0 items-center gap-3">
                <div className={`${compact ? "h-6 w-6" : "h-7 w-7"} flex shrink-0 items-center justify-center overflow-hidden rounded-full border border-slate-200 bg-slate-50 text-[10px] font-black text-slate-500`}>
                  {row.logo ? <img src={row.logo} alt="chain logo" className="h-full w-full object-cover" /> : getInitials(row.name)}
                </div>
                <div className={`${compact ? "text-sm" : "text-base"} truncate font-black text-slate-950`}>{row.name}</div>
              </div>
              <div className={`${compact ? "h-2.5" : "h-3.5"} rounded-full bg-slate-100`}><div className={`${compact ? "h-2.5" : "h-3.5"} rounded-full bg-slate-950`} style={{ width: `${pct}%` }} /></div>
              <div className="text-right text-sm font-black text-slate-950 md:text-base">{formatUsd(row.value)}</div>
            </div>
          );
        })}
      </div>

      <div className="mt-9 rounded-[24px] bg-slate-950 p-5 text-white shadow-sm">
        <p className="text-sm font-medium leading-7 text-slate-200 md:text-base"><span className="font-black text-white">Insight note:</span> {leader?.name ?? "The leading chain"} leads {timeframe} chain revenue{runnerUp ? `, followed by ${runnerUp.name}.` : "."} This card measures revenue captured by chains only.</p>
      </div>

      <div className="mt-7 grid gap-3 text-xs font-bold text-slate-400 md:grid-cols-[1fr_2fr] md:items-end">
        <span>Generated by <span className="font-black text-slate-950">learnDeFi</span></span>
        <span className="md:text-right">Data: {source} · Updated: <span className="font-black text-slate-700">{updatedAt}</span></span>
      </div>
    </div>
  );
}
