"use client";

import { formatUsd } from "@/lib/format";
import type { ChainRevenueRow } from "@/lib/defillama";

export function ShareCard({
  rows,
  timeframe,
  updatedAt,
  source,
}: {
  rows: ChainRevenueRow[];
  timeframe: string;
  updatedAt: string;
  source: string;
}) {
  const leader = rows[0];

  return (
    <div
      id="share-card"
      className="card-grid-bg relative overflow-hidden rounded-[32px] border border-slate-200 bg-white p-8 shadow-soft"
    >
      <div className="absolute right-8 top-8 rounded-full border border-slate-200 bg-white/90 px-4 py-2 text-xs font-black tracking-[-0.02em] text-slate-900">
        learnDeFi
      </div>

      <div className="max-w-[72%]">
        <p className="text-sm font-bold uppercase tracking-[0.22em] text-slate-400">
          Chain Revenue
        </p>
        <h2 className="mt-2 text-4xl font-black tracking-[-0.04em] text-slate-950">
          Top chains by {timeframe} revenue
        </h2>
        <p className="mt-3 text-sm leading-6 text-slate-500">
          A clean AI-ready view of chain-level revenue captured by networks.
        </p>
      </div>

      <div className="mt-8 grid gap-3">
        {rows.slice(0, 10).map((row) => {
          const pct = leader?.value ? Math.max(7, (row.value / leader.value) * 100) : 0;

          return (
            <div
              key={row.name}
              className="grid grid-cols-[36px_150px_1fr_104px] items-center gap-3"
            >
              <div className="text-right text-sm font-bold text-slate-400">
                {row.rank}
              </div>
              <div className="truncate text-base font-bold text-slate-900">
                {row.name}
              </div>
              <div className="h-3 rounded-full bg-slate-100">
                <div
                  className="h-3 rounded-full bg-slate-950"
                  style={{ width: `${pct}%` }}
                />
              </div>
              <div className="text-right text-sm font-black text-slate-900">
                {formatUsd(row.value)}
              </div>
            </div>
          );
        })}
      </div>

      <div className="mt-8 rounded-2xl bg-slate-950 p-4 text-white">
        <p className="text-sm leading-6 text-slate-200">
          <span className="font-bold text-white">AI note:</span>{" "}
          {leader?.name ?? "The leading chain"} currently leads this chain revenue
          ranking. This view focuses on revenue captured by chains, not dApp or
          protocol revenue.
        </p>
      </div>

      <div className="mt-6 flex items-center justify-between gap-4 text-xs font-semibold text-slate-400">
        <span>Generated by learnDeFi</span>
        <span className="text-right">Data: {source} · Updated: {updatedAt}</span>
      </div>
    </div>
  );
}
