export type PublicBrandSettings = {
  siteName: string;
  shortName: string;
  mainSlogan: string;
  heroSubtitle: string;
  supportingCopy: string;
  cardFooterText: string;
  createdWithText: string;
  metaDescription: string;
  primaryLogo: string;
  darkLogo: string;
  iconMark: string;
  headerLogo: string;
  favicon: string;
  appleTouchIcon: string;
  xAvatar: string;
  xBanner: string;
  watermarkMark: string;
  heroLogoOffsetX: string;
  heroLogoMaxWidth: string;
  heroLogoSpacing: string;
  assetMetadata?: Record<string, { provider: "manual-url" | "upload" | "disabled"; kind: string; fileSize?: number; mimeType?: string; uploadedAt?: string; url?: string }>;
  savedAt?: string;
};
