export type DatasetCategory = 'chains' | 'protocols' | 'capital-flows' | 'markets';
export type DatasetStatus = 'active' | 'source_config_required' | 'source_error' | 'stale' | 'disabled' | 'planned';
export type FreshnessStatus = 'fresh' | 'stale' | 'missing' | 'source_error' | 'manual_review_required' | 'source_config_required';

export type DatasetRegistryItem = {
  id: string; name: string; slug: string; category: DatasetCategory; description: string; frequency: string;
  sources: string[]; primarySource: string; fallbackSources: string[]; requiredEnv: string[];
  refreshPolicy: string; requiredFields: string[]; derivedMetrics: string[]; chartTemplates: string[];
  status: DatasetStatus; sourceLabel: string; notes?: string; defaultPeriod: string; supportedPeriods: string[];
};

const has = (k: string) => Boolean(process.env[k]);
const cfg = (...keys: string[]) => keys.every(has);

export const datasetRegistry: DatasetRegistryItem[] = [
  { id:'chain-revenue-league',name:'Chain Revenue League',slug:'chain-revenue-league',category:'chains',description:'Top chains by captured chain-level revenue.',frequency:'daily',sources:['defillama'],primarySource:'defillama',fallbackSources:[],requiredEnv:[],refreshPolicy:'6h snapshot',requiredFields:['chain','revenue_24h','revenue_7d','revenue_30d'],derivedMetrics:['market_share','rank_change'],chartTemplates:['leaderboard_bar','metric_cards','insight_chips'],status:'active',sourceLabel:'Source: DefiLlama',defaultPeriod:'7d',supportedPeriods:['24h','7d','30d'] },
  { id:'chain-stablecoin-supply',name:'Chain Stablecoin Supply',slug:'chain-stablecoin-supply',category:'chains',description:'Stablecoin supply by chain.',frequency:'daily',sources:['defillama'],primarySource:'defillama',fallbackSources:[],requiredEnv:[],refreshPolicy:'daily snapshot',requiredFields:['chain','supply'],derivedMetrics:['market_share','rank_change'],chartTemplates:['leaderboard_bar','market_share_cards'],status:'active',sourceLabel:'Source: DefiLlama',defaultPeriod:'30d',supportedPeriods:['7d','30d','monthly'] },
  { id:'stablecoin-net-transfers-by-chain',name:'Stablecoin Net Transfers by Chain',slug:'stablecoin-net-transfers-by-chain',category:'chains',description:'Dune net stablecoin flows by chain.',frequency:'daily',sources:['dune'],primarySource:'dune',fallbackSources:[],requiredEnv:['DUNE_API_KEY','DUNE_STABLECOIN_NET_TRANSFERS_QUERY_ID'],refreshPolicy:'scheduled refresh only',requiredFields:['chain','net_transfer_7d','net_transfer_30d'],derivedMetrics:['largest_inflow','largest_outflow'],chartTemplates:['stablecoin_flow_board'],status:cfg('DUNE_API_KEY','DUNE_STABLECOIN_NET_TRANSFERS_QUERY_ID')?'active':'source_config_required',sourceLabel:'Source: Dune',defaultPeriod:'7d',supportedPeriods:['7d','30d'] },
  { id:'dex-volume-by-chain',name:'DEX Volume by Chain',slug:'dex-volume-by-chain',category:'chains',description:'DEX volume by chain.',frequency:'daily',sources:['defillama'],primarySource:'defillama',fallbackSources:[],requiredEnv:[],refreshPolicy:'6h snapshot',requiredFields:['chain','volume_24h','volume_7d'],derivedMetrics:['market_share','rank_change'],chartTemplates:['leaderboard_bar'],status:'active',sourceLabel:'Source: DefiLlama',defaultPeriod:'7d',supportedPeriods:['24h','7d','30d'] },
  { id:'protocol-revenue-league',name:'Protocol Revenue League',slug:'protocol-revenue-league',category:'protocols',description:'Top protocols by revenue.',frequency:'daily',sources:['defillama'],primarySource:'defillama',fallbackSources:[],requiredEnv:[],refreshPolicy:'6h snapshot',requiredFields:['protocol','revenue_24h'],derivedMetrics:['market_share','rank_change'],chartTemplates:['leaderboard_bar'],status:'active',sourceLabel:'Source: DefiLlama',defaultPeriod:'7d',supportedPeriods:['24h','7d','30d'] },
  { id:'dex-protocol-volume',name:'DEX Protocol Volume',slug:'dex-protocol-volume',category:'protocols',description:'DEX volume by protocol.',frequency:'daily',sources:['defillama'],primarySource:'defillama',fallbackSources:[],requiredEnv:[],refreshPolicy:'6h snapshot',requiredFields:['protocol','volume_24h'],derivedMetrics:['market_share'],chartTemplates:['leaderboard_bar'],status:'active',sourceLabel:'Source: DefiLlama',defaultPeriod:'7d',supportedPeriods:['24h','7d','30d'] },
  { id:'perp-protocol-volume-oi',name:'Perp Protocol Volume & OI',slug:'perp-protocol-volume-oi',category:'protocols',description:'Perp protocol volume and open interest.',frequency:'daily',sources:['defillama'],primarySource:'defillama',fallbackSources:[],requiredEnv:[],refreshPolicy:'6h snapshot',requiredFields:['protocol','volume_24h'],derivedMetrics:['market_share'],chartTemplates:['leaderboard_bar'],status:'active',sourceLabel:'Source: DefiLlama',defaultPeriod:'24h',supportedPeriods:['24h','7d','30d'] },
  { id:'btc-etf-flowboard',name:'BTC ETF Flowboard',slug:'btc-etf-flowboard',category:'capital-flows',description:'BTC ETF daily net flows.',frequency:'daily',sources:['farside'],primarySource:'farside',fallbackSources:['defillama'],requiredEnv:[],refreshPolicy:'daily refresh',requiredFields:['date','issuer','net_flow'],derivedMetrics:['rolling_5d','rolling_20d'],chartTemplates:['etf_flowboard'],status:'active',sourceLabel:'Source: Farside',defaultPeriod:'weekly',supportedPeriods:['weekly','monthly'] },
  { id:'eth-etf-flowboard',name:'ETH ETF Flowboard',slug:'eth-etf-flowboard',category:'capital-flows',description:'ETH ETF daily net flows.',frequency:'daily',sources:['farside'],primarySource:'farside',fallbackSources:['defillama'],requiredEnv:[],refreshPolicy:'daily refresh',requiredFields:['date','issuer','net_flow'],derivedMetrics:['rolling_5d','rolling_20d'],chartTemplates:['etf_flowboard'],status:'active',sourceLabel:'Source: Farside',defaultPeriod:'weekly',supportedPeriods:['weekly','monthly'] },
  { id:'btc-vs-eth-etf-flow-battle',name:'BTC vs ETH ETF Flow Battle',slug:'btc-vs-eth-etf-flow-battle',category:'capital-flows',description:'BTC vs ETH ETF flow comparison.',frequency:'daily',sources:['farside','binance'],primarySource:'farside',fallbackSources:[],requiredEnv:[],refreshPolicy:'daily refresh',requiredFields:['btc_weekly_flow','eth_weekly_flow'],derivedMetrics:['flow_as_percent_of_aum'],chartTemplates:['btc_eth_comparison'],status:'active',sourceLabel:'Source: Farside + Binance',defaultPeriod:'weekly',supportedPeriods:['weekly','monthly'] },
  { id:'etf-issuer-monthly-report',name:'ETF Issuer Monthly Report',slug:'etf-issuer-monthly-report',category:'capital-flows',description:'Monthly ETF issuer leaderboard.',frequency:'monthly',sources:['farside'],primarySource:'farside',fallbackSources:['defillama'],requiredEnv:[],refreshPolicy:'daily refresh',requiredFields:['issuer','monthly_flow'],derivedMetrics:['market_share'],chartTemplates:['leaderboard_bar'],status:'active',sourceLabel:'Source: Farside',defaultPeriod:'monthly',supportedPeriods:['monthly'] },
  { id:'cex-transparency',name:'CEX Transparency',slug:'cex-transparency',category:'capital-flows',description:'Exchange reserves and flow panel.',frequency:'daily',sources:['defillama'],primarySource:'defillama',fallbackSources:[],requiredEnv:[],refreshPolicy:'daily snapshot',requiredFields:['exchange','assets'],derivedMetrics:['rank_change'],chartTemplates:['leaderboard_bar'],status:'active',sourceLabel:'Source: DefiLlama',defaultPeriod:'7d',supportedPeriods:['24h','7d','30d'] },
  { id:'digital-asset-treasuries',name:'Digital Asset Treasuries',slug:'digital-asset-treasuries',category:'capital-flows',description:'Digital asset treasury leaderboard.',frequency:'daily',sources:['defillama'],primarySource:'defillama',fallbackSources:[],requiredEnv:[],refreshPolicy:'daily snapshot',requiredFields:['entity','asset','amount'],derivedMetrics:['monthly_change'],chartTemplates:['leaderboard_bar'],status:'active',sourceLabel:'Source: DefiLlama',defaultPeriod:'monthly',supportedPeriods:['monthly'] },
  { id:'monthly-unlock-watch',name:'Monthly Unlock Watch',slug:'monthly-unlock-watch',category:'capital-flows',description:'Token unlock calendar and pressure.',frequency:'daily',sources:['defillama'],primarySource:'defillama',fallbackSources:[],requiredEnv:[],refreshPolicy:'daily snapshot',requiredFields:['token','unlock_date','unlock_value_usd'],derivedMetrics:['supply_pressure_score'],chartTemplates:['unlock_calendar'],status:'active',sourceLabel:'Source: DefiLlama',defaultPeriod:'monthly',supportedPeriods:['monthly'] },
  { id:'large-holders-board',name:'Large Holders Board',slug:'large-holders-board',category:'capital-flows',description:'BTC/ETH large holder concentration.',frequency:'daily',sources:['etherscan'],primarySource:'etherscan',fallbackSources:[],requiredEnv:['ETHERSCAN_API_KEY'],refreshPolicy:'daily snapshot',requiredFields:['address','balance'],derivedMetrics:['dominance'],chartTemplates:['holder_concentration'],status:has('ENABLE_LARGE_HOLDERS')&&has('ETHERSCAN_API_KEY')?'active':'source_config_required',sourceLabel:'Source: Etherscan/Public',defaultPeriod:'daily',supportedPeriods:['daily'] },
  { id:'whale-transfers',name:'Whale Transfers',slug:'whale-transfers',category:'capital-flows',description:'Largest daily whale transfers.',frequency:'hourly',sources:['whalealert','etherscan'],primarySource:'whalealert',fallbackSources:['etherscan'],requiredEnv:['ENABLE_WHALE_TRANSFERS'],refreshPolicy:'hourly snapshot',requiredFields:['asset','amount','usd_value','tx_hash'],derivedMetrics:['largest_inflow','largest_outflow'],chartTemplates:['whale_transfer_cards'],status:(has('ENABLE_WHALE_TRANSFERS')&&(has('WHALE_ALERT_API_KEY')||has('ETHERSCAN_API_KEY')))?'active':'source_config_required',sourceLabel:'Source: Whale Alert / Etherscan',defaultPeriod:'24h',supportedPeriods:['24h'] },
  { id:'binance-liquidation-pulse',name:'Binance Liquidation Pulse',slug:'binance-liquidation-pulse',category:'markets',description:'Captured Binance Futures liquidations only.',frequency:'hourly',sources:['binance'],primarySource:'binance',fallbackSources:[],requiredEnv:['ENABLE_BINANCE_LIQUIDATION_PULSE'],refreshPolicy:'collector snapshot',requiredFields:['symbol','side','usd_value'],derivedMetrics:['long_short_imbalance'],chartTemplates:['liquidation_pulse'],status:has('ENABLE_BINANCE_LIQUIDATION_PULSE')?'active':'source_config_required',sourceLabel:'Source: Binance Futures',defaultPeriod:'24h',supportedPeriods:['1h','4h','24h'] },
];

export const categories = [{id:'chains',name:'Chains'},{id:'protocols',name:'Protocols'},{id:'capital-flows',name:'Capital Flows'},{id:'markets',name:'Markets'}] as const;
export const datasetsByCategory = categories.map((category) => ({ ...category, datasets: datasetRegistry.filter((dataset) => dataset.category === category.id) }));
