"use client";
import { Bar, BarChart, LabelList, ResponsiveContainer, XAxis, YAxis } from "recharts";
import { MetricCard, SourceConfigRequiredState } from "../ChartShell";
const usd = (v:any)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(Number(v)||0);
export function StablecoinFlowBoard({ data }: { data:any }) { if(data.status==='source_config_required') return <SourceConfigRequiredState missingConfig={data.freshness?.missingConfig||[]} message={data.freshness?.message}/>; const bars=(data.series?.bars||[]).slice(0,12); return <><div className="grid grid-cols-3 gap-4">{(data.headlineMetrics||[]).slice(0,3).map((m:any)=><MetricCard key={m.label} label={m.label} value={m.formattedValue}/>)}</div><div className="mt-7 grid grid-cols-5 gap-6"><div className="col-span-3 h-[480px] rounded-3xl border bg-white p-6"><h3 className="mb-4 text-sm uppercase tracking-[0.2em] text-zinc-500">Chain supply leaderboard</h3><ResponsiveContainer width="100%" height="88%"><BarChart data={bars} layout="vertical" margin={{left:14,right:86,top:4,bottom:4}}><XAxis type="number" hide/><YAxis type="category" dataKey="name" width={150} tick={{fontSize:14,fill:'#18181b'}} tickLine={false} axisLine={false}/><Bar dataKey="value" fill="#10b981" radius={[0,12,12,0]} isAnimationActive={false} activeBar={false as any}><LabelList dataKey="value" position="right" formatter={usd as any} style={{ fill:'#3f3f46', fontSize:12, fontWeight:600 }}/></Bar></BarChart></ResponsiveContainer></div><div className="col-span-2 grid content-start gap-3">{bars.slice(0,5).map((r:any)=><div key={r.name} className="rounded-2xl border border-zinc-200 bg-white p-4"><div className="flex items-center justify-between"><span className="font-semibold text-zinc-900">{r.name}</span><span className="text-sm font-semibold text-emerald-700">{usd(r.value)}</span></div>{Number(r.usdc || r.usdt) > 0 ? <div className="mt-2 text-xs text-zinc-500">USDC {usd(r.usdc)} · USDT {usd(r.usdt)}</div> : <div className="mt-2 text-xs text-zinc-500">Issuer split unavailable for this row.</div>}</div>)}</div></div></>; }
export function UnlockCalendar({ data }: { data:any }) { return <SourceConfigRequiredState missingConfig={data.freshness?.missingConfig||[]} message={data.freshness?.message}/>; }
export function LiquidationPulse({ data }: { data:any }) { return <SourceConfigRequiredState missingConfig={data.freshness?.missingConfig||[]} message={data.freshness?.message}/>; }
export function HolderConcentration({ data }: { data:any }) { return <SourceConfigRequiredState missingConfig={data.freshness?.missingConfig||[]} message={data.freshness?.message}/>; }
export function WhaleTransferCards({ data }: { data:any }) { return <SourceConfigRequiredState missingConfig={data.freshness?.missingConfig||[]} message={data.freshness?.message}/>; }
