export const coingeckoLogoIds: Record<string, string | null> = {
  ethereum: "ethereum",
  tron: "tron",
  bsc: "binancecoin",
  "bnb-chain": "binancecoin",
  solana: "solana",
  hyperliquid: "hyperliquid",
  base: "base",
  arbitrum: "arbitrum",
  polygon: "polygon-ecosystem-token",
  avalanche: "avalanche-2",
  aptos: "aptos",
  ton: "the-open-network",
  optimism: "optimism",
  "op-mainnet": "optimism",
  mantle: "mantle",
  sui: "sui",
  ripple: "ripple",
  "xrp-ledger": "ripple",
  monad: "monad",
  stellar: "stellar",
  fantom: "fantom",
  sei: "sei-network",
  starknet: "starknet",
  ink: "ink",
  cronos: "crypto-com-chain",
  celo: "celo",
  cardano: "cardano",
  near: "near",
  injective: "injective-protocol",
  "internet-computer": "internet-computer",
  filecoin: "filecoin",
  akash: "akash-network",
  "render-network": "render-token",
  "render": "render-token",
  helium: "helium",
  livepeer: "livepeer",
  "bsv-blockchain": "bitcoin-sv",
  geodnet: "geodnet",
  glow: null,
  "io-net": "io-net",
  "io.net": "io-net",
  dimo: "dimo",
  "pocket-network": "pocket-network",
  canton: null,
  morph: "morph-2",
  abstract: null,
  linea: "linea",
  plume: null,
  plasma: null,
  megaeth: null,
  "mega-eth": null,
  provenance: null,
  eni: null,
};

export function getCoinGeckoLogoId(slug: string) {
  return coingeckoLogoIds[slug] ?? null;
}
