import type { DatasetRegistryItem } from './types';

const has = (key: string) => Boolean(process.env[key]);
const hasAll = (...keys: string[]) => keys.every(has);

export const datasetRegistry: DatasetRegistryItem[] = [
  { id:'chain-revenue-league',name:'Chain Fees League',slug:'chain-revenue-league',category:'chains',description:'Top chains by network-level fees from DefiLlama chain breakdowns; protocol revenue is excluded.',frequency:'daily',sources:['defillama'],primarySource:'defillama',fallbackSources:[],requiredEnv:[],refreshPolicy:'6h snapshot',requiredFields:['chain','fees_24h','fees_7d','fees_30d'],derivedMetrics:['market_share','rank_change'],chartTemplates:['leaderboard_bar'],status:'active',sourceLabel:'Source: DefiLlama',defaultPeriod:'7d',supportedPeriods:['24h','7d','30d'] },
  { id:'chain-stablecoin-supply',name:'Chain Stablecoin Supply',slug:'chain-stablecoin-supply',category:'chains',description:'Stablecoin supply by chain, including issuer splits where available.',frequency:'daily',sources:['defillama'],primarySource:'defillama',fallbackSources:[],requiredEnv:[],refreshPolicy:'daily snapshot',requiredFields:['chain','supply','market_share'],derivedMetrics:['market_share'],chartTemplates:['stablecoin_flow_board','leaderboard_bar'],status:'active',sourceLabel:'Source: DefiLlama',defaultPeriod:'30d',supportedPeriods:['7d','30d','monthly'] },
  { id:'stablecoin-net-transfers-by-chain',name:'Stablecoin Net Transfers by Chain',slug:'stablecoin-net-transfers-by-chain',category:'chains',description:'Dune latest-result snapshot of stablecoin inflows, outflows, and net transfers by chain.',frequency:'daily',sources:['dune'],primarySource:'dune',fallbackSources:[],requiredEnv:['DUNE_API_KEY','DUNE_STABLECOIN_NET_TRANSFERS_QUERY_ID'],refreshPolicy:'scheduled/manual refresh only; never executes query on page load',requiredFields:['chain','inflow','outflow','net_flow'],derivedMetrics:['largest_inflow','largest_outflow'],chartTemplates:['stablecoin_flow_board'],status:'source_config_required',sourceLabel:'Source: Dune latest result',defaultPeriod:'7d',supportedPeriods:['7d','30d'] },
  { id:'dex-volume-by-chain',name:'DEX Volume by Chain',slug:'dex-volume-by-chain',category:'chains',description:'DEX volume by chain from DefiLlama.',frequency:'daily',sources:['defillama'],primarySource:'defillama',fallbackSources:[],requiredEnv:[],refreshPolicy:'6h snapshot',requiredFields:['chain','volume_24h','volume_7d','volume_30d'],derivedMetrics:['market_share','rank_change'],chartTemplates:['leaderboard_bar'],status:'active',sourceLabel:'Source: DefiLlama',defaultPeriod:'7d',supportedPeriods:['24h','7d','30d'] },
  { id:'protocol-revenue-league',name:'Protocol Revenue League',slug:'protocol-revenue-league',category:'protocols',description:'Protocol revenue leaderboard from DefiLlama fees/revenue.',frequency:'daily',sources:['defillama'],primarySource:'defillama',fallbackSources:[],requiredEnv:[],refreshPolicy:'6h snapshot',requiredFields:['protocol','revenue_24h','revenue_7d','revenue_30d'],derivedMetrics:['market_share','rank_change'],chartTemplates:['leaderboard_bar'],status:'active',sourceLabel:'Source: DefiLlama',defaultPeriod:'7d',supportedPeriods:['24h','7d','30d'] },
  { id:'dex-protocol-volume',name:'DEX Protocol Volume',slug:'dex-protocol-volume',category:'protocols',description:'DEX protocol volume leaderboard from DefiLlama.',frequency:'daily',sources:['defillama'],primarySource:'defillama',fallbackSources:[],requiredEnv:[],refreshPolicy:'6h snapshot',requiredFields:['protocol','volume_24h','volume_7d','volume_30d'],derivedMetrics:['market_share'],chartTemplates:['leaderboard_bar'],status:'active',sourceLabel:'Source: DefiLlama',defaultPeriod:'7d',supportedPeriods:['24h','7d','30d'] },
  { id:'perp-protocol-volume-oi',name:'Perp Protocol Volume & OI',slug:'perp-protocol-volume-oi',category:'protocols',description:'Perp protocol volume and open interest where available from DefiLlama derivatives.',frequency:'daily',sources:['defillama'],primarySource:'defillama',fallbackSources:[],requiredEnv:[],refreshPolicy:'6h snapshot',requiredFields:['protocol','volume_24h','open_interest'],derivedMetrics:['market_share'],chartTemplates:['leaderboard_bar'],status:'active',sourceLabel:'Source: DefiLlama',defaultPeriod:'24h',supportedPeriods:['24h','7d','30d'] },
  { id:'btc-etf-flowboard',name:'BTC ETF Flowboard',slug:'btc-etf-flowboard',category:'capital-flows',description:'BTC spot ETF daily, weekly, and monthly issuer flows parsed from Farside.',frequency:'daily',sources:['farside','binance'],primarySource:'farside',fallbackSources:['binance'],requiredEnv:[],refreshPolicy:'daily refresh',requiredFields:['date','issuer','net_flow'],derivedMetrics:['rolling_5d','rolling_20d','cumulative_flow','streak'],chartTemplates:['etf_flowboard'],status:'active',sourceLabel:'Farside Investors + Binance',defaultPeriod:'daily',supportedPeriods:['daily','weekly','monthly'] },
  { id:'eth-etf-flowboard',name:'ETH ETF Flowboard',slug:'eth-etf-flowboard',category:'capital-flows',description:'ETH spot ETF daily issuer flows parsed from Farside.',frequency:'daily',sources:['farside','binance'],primarySource:'farside',fallbackSources:['binance'],requiredEnv:[],refreshPolicy:'daily refresh',requiredFields:['date','issuer','net_flow'],derivedMetrics:['rolling_5d','rolling_20d','cumulative_flow','streak'],chartTemplates:['etf_flowboard'],status:'active',sourceLabel:'Farside Investors + Binance',defaultPeriod:'weekly',supportedPeriods:['weekly','monthly'] },
  { id:'btc-vs-eth-etf-flow-battle',name:'BTC vs ETH ETF Flow Battle',slug:'btc-vs-eth-etf-flow-battle',category:'capital-flows',description:'BTC and ETH ETF flow comparison using the same Farside parser.',frequency:'daily',sources:['farside','binance'],primarySource:'farside',fallbackSources:['binance'],requiredEnv:[],refreshPolicy:'daily refresh',requiredFields:['btc_weekly_flow','eth_weekly_flow'],derivedMetrics:['winner','rolling_5d','rolling_20d'],chartTemplates:['btc_eth_comparison'],status:'active',sourceLabel:'Farside Investors + Binance',defaultPeriod:'weekly',supportedPeriods:['weekly','monthly'] },
  { id:'etf-issuer-monthly-report',name:'ETF Issuer Monthly Report',slug:'etf-issuer-monthly-report',category:'capital-flows',description:'Monthly ETF issuer net-flow leaderboard from BTC and ETH Farside tables.',frequency:'monthly',sources:['farside'],primarySource:'farside',fallbackSources:[],requiredEnv:[],refreshPolicy:'daily refresh',requiredFields:['issuer','monthly_flow','asset'],derivedMetrics:['market_share'],chartTemplates:['leaderboard_bar'],status:'active',sourceLabel:'Farside Investors',defaultPeriod:'monthly',supportedPeriods:['monthly'] },
  { id:'cex-transparency',name:'CEX Transparency',slug:'cex-transparency',category:'capital-flows',description:'Exchange reserves transparency from DefiLlama CEX endpoints.',frequency:'daily',sources:['defillama'],primarySource:'defillama',fallbackSources:[],requiredEnv:[],refreshPolicy:'daily snapshot',requiredFields:['exchange','assets'],derivedMetrics:['rank_change'],chartTemplates:['leaderboard_bar'],status:'active',sourceLabel:'Source: DefiLlama',defaultPeriod:'7d',supportedPeriods:['24h','7d','30d'] },
  { id:'digital-asset-treasuries',name:'Digital Asset Treasuries',slug:'digital-asset-treasuries',category:'capital-flows',description:'Digital asset treasury data requires a licensed/source-specific provider before activation.',frequency:'daily',sources:['treasury_config'],primarySource:'treasury_config',fallbackSources:[],requiredEnv:['DIGITAL_ASSET_TREASURIES_SOURCE_URL'],refreshPolicy:'configured snapshot import',requiredFields:['entity','asset','amount','market_value_usd'],derivedMetrics:['monthly_change'],chartTemplates:['leaderboard_bar'],status:has('DIGITAL_ASSET_TREASURIES_SOURCE_URL')?'source_config_required':'disabled',sourceLabel:'Source: configured treasury provider',notes:'Disabled until a reliable provider URL/schema is configured; no fake treasury data is emitted.',defaultPeriod:'monthly',supportedPeriods:['monthly'] },
  { id:'monthly-unlock-watch',name:'Monthly Unlock Watch',slug:'monthly-unlock-watch',category:'capital-flows',description:'Token unlock calendar requires a configured unlock data source before activation.',frequency:'daily',sources:['unlock_config'],primarySource:'unlock_config',fallbackSources:[],requiredEnv:['TOKEN_UNLOCKS_SOURCE_URL'],refreshPolicy:'configured snapshot import',requiredFields:['token','unlock_date','unlock_value_usd'],derivedMetrics:['supply_pressure_score'],chartTemplates:['unlock_calendar'],status:has('TOKEN_UNLOCKS_SOURCE_URL')?'source_config_required':'disabled',sourceLabel:'Source: configured unlock provider',notes:'Disabled until an unlock source URL with redistribution rights is configured; no fake unlocks are emitted.',defaultPeriod:'monthly',supportedPeriods:['monthly'] },
  { id:'large-holders-board',name:'Large Holders Board',slug:'large-holders-board',category:'capital-flows',description:'Large holder concentration from configured chain explorer sources.',frequency:'daily',sources:['etherscan'],primarySource:'etherscan',fallbackSources:[],requiredEnv:['ETHERSCAN_API_KEY'],refreshPolicy:'daily snapshot',requiredFields:['address','balance'],derivedMetrics:['dominance'],chartTemplates:['holder_concentration'],status:has('ETHERSCAN_API_KEY')?'source_config_required':'source_config_required',sourceLabel:'Source: Etherscan',defaultPeriod:'daily',supportedPeriods:['daily'] },
  { id:'whale-transfers',name:'Whale Transfers',slug:'whale-transfers',category:'capital-flows',description:'Whale transfers from Whale Alert or explorer APIs after credentials are configured.',frequency:'hourly',sources:['whalealert','etherscan'],primarySource:'whalealert',fallbackSources:['etherscan'],requiredEnv:['WHALE_ALERT_API_KEY'],refreshPolicy:'hourly snapshot',requiredFields:['asset','amount','usd_value','tx_hash'],derivedMetrics:['largest_inflow','largest_outflow'],chartTemplates:['whale_transfer_cards'],status:(has('WHALE_ALERT_API_KEY')||has('ETHERSCAN_API_KEY'))?'source_config_required':'source_config_required',sourceLabel:'Source: Whale Alert / Etherscan',defaultPeriod:'24h',supportedPeriods:['24h'] },
  { id:'binance-liquidation-pulse',name:'Binance Liquidation Pulse',slug:'binance-liquidation-pulse',category:'markets',description:'Captured Binance Futures liquidation events only; not market-wide liquidations.',frequency:'hourly',sources:['binance'],primarySource:'binance',fallbackSources:[],requiredEnv:['ENABLE_BINANCE_LIQUIDATION_PULSE'],refreshPolicy:'external collector snapshot',requiredFields:['symbol','side','usd_value'],derivedMetrics:['long_short_imbalance'],chartTemplates:['liquidation_pulse'],status:has('ENABLE_BINANCE_LIQUIDATION_PULSE')?'source_config_required':'source_config_required',sourceLabel:'Source: Binance Futures collector',defaultPeriod:'24h',supportedPeriods:['1h','4h','24h'] },
];

export const categories = [{id:'chains',name:'Chains'},{id:'protocols',name:'Protocols'},{id:'capital-flows',name:'Capital Flows'},{id:'markets',name:'Markets'}] as const;
export const datasetsByCategory = categories.map((category) => ({ ...category, datasets: datasetRegistry.filter((dataset) => dataset.category === category.id) }));
