import { datasetRegistry } from './registry';
import { loadSourceRuns } from './storage';

const sourceEnv: Record<string, string[]> = { dune:['DUNE_API_KEY','DUNE_STABLECOIN_NET_TRANSFERS_QUERY_ID'], binance:['ENABLE_BINANCE_LIQUIDATION_PULSE'], etherscan:['ETHERSCAN_API_KEY'], whalealert:['WHALE_ALERT_API_KEY'], treasury_config:['DIGITAL_ASSET_TREASURIES_SOURCE_URL'], unlock_config:['TOKEN_UNLOCKS_SOURCE_URL'], defillama:[], farside:[] };
export async function getSourceHealth({ detailed = false } = {}) {
  const runs = await loadSourceRuns();
  const sources = [...new Set(datasetRegistry.flatMap((d)=>d.sources))].sort();
  return { generatedAt:new Date().toISOString(), sources:sources.map((source)=>{ const datasets = datasetRegistry.filter((d)=>d.sources.includes(source) || d.primarySource === source); const env = sourceEnv[source] || []; const missingEnv = env.filter((key)=>!process.env[key]); const sourceRuns = runs.filter((r)=>r.source.toLowerCase().includes(source.replace('_config','').toLowerCase()) || datasets.some((d)=>d.slug === r.datasetSlug)); const lastSuccess = sourceRuns.find((r)=>r.status === 'success') || null; const lastFail = sourceRuns.find((r)=>r.status === 'source_error') || null; const staleDatasets = datasets.filter((d)=>['stale','source_error'].includes(d.status)).map((d)=>d.slug); const manual = datasets.filter((d)=>d.status === 'disabled' || d.status === 'source_config_required').map((d)=>d.slug); return { source, configured:missingEnv.length === 0, missingEnv, datasets:datasets.map((d)=>d.slug), datasetStatuses:Object.fromEntries(datasets.map((d)=>[d.slug,d.status])), lastSuccessfulFetch:lastSuccess?.finishedAt || null, lastFailedFetch:lastFail?.finishedAt || null, lastError:lastFail?.errorMessage || null, staleDatasets, manual_review_required:manual, warnings:[...missingEnv.map((key)=>`${key} is not configured`), ...datasets.filter((d)=>d.notes).map((d)=>`${d.slug}: ${d.notes}`)], ...(detailed ? { recentRuns:sourceRuns.slice(0,10) } : {}) }; }) };
}
